spring.application.name=auth

server.port=${PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# update crea las tablas que falten (VENTAS / DETALLES_VENTAS).
# Cuando el esquema ya coincida con las entidades, puedes volver a validate.
spring.jpa.hibernate.ddl-auto=create-drop
